// This file is autogenerated by CMake. Do not edit.

#include <QtCore/qtsymbolmacros.h>
#include <QtQml/qqmlextensionplugin.h>


QT_DECLARE_EXTERN_RESOURCE(qmlcache_Design)
QT_DECLARE_EXTERN_RESOURCE(qmake_Design)
QT_DECLARE_EXTERN_RESOURCE(Design_raw_qml_0)


QT_DECLARE_EXTERN_SYMBOL_VOID(qml_register_types_Design)

class DesignPlugin : public QQmlEngineExtensionPlugin
{
    Q_OBJECT
    Q_PLUGIN_METADATA(IID QQmlEngineExtensionInterface_iid)

public:
    DesignPlugin(QObject *parent = nullptr) : QQmlEngineExtensionPlugin(parent)
    {

QT_KEEP_SYMBOL(qml_register_types_Design)
QT_KEEP_RESOURCE(qmlcache_Design)
QT_KEEP_RESOURCE(qmake_Design)
QT_KEEP_RESOURCE(Design_raw_qml_0)
    }
};



#include "Designplugin_DesignPlugin.moc"
