// This file is autogenerated by CMake. Do not edit.

#include <QtCore/qtsymbolmacros.h>
#include <QtQml/qqmlextensionplugin.h>


QT_DECLARE_EXTERN_RESOURCE(qmlcache_DesignContent)
QT_DECLARE_EXTERN_RESOURCE(qmake_DesignContent)
QT_DECLARE_EXTERN_RESOURCE(DesignContent_raw_qml_0)


QT_DECLARE_EXTERN_SYMBOL_VOID(qml_register_types_DesignContent)

class DesignContentPlugin : public QQmlEngineExtensionPlugin
{
    Q_OBJECT
    Q_PLUGIN_METADATA(IID QQmlEngineExtensionInterface_iid)

public:
    DesignContentPlugin(QObject *parent = nullptr) : QQmlEngineExtensionPlugin(parent)
    {

QT_KEEP_SYMBOL(qml_register_types_DesignContent)
QT_KEEP_RESOURCE(qmlcache_DesignContent)
QT_KEEP_RESOURCE(qmake_DesignContent)
QT_KEEP_RESOURCE(DesignContent_raw_qml_0)
    }
};



#include "DesignContentplugin_DesignContentPlugin.moc"
